section: screens
        psiegel-desktop:
                halfDuplexCapsLock = false
                halfDuplexNumLock = false
                halfDuplexScrollLock = false
                xtestIsXineramaUnaware = false
                preserveFocus = false
                switchCorners = none
                switchCornerSize = 0
        psiegel-laptop:
                halfDuplexCapsLock = false
                halfDuplexNumLock = false
                halfDuplexScrollLock = false
                xtestIsXineramaUnaware = false
                preserveFocus = false
                switchCorners = none
                switchCornerSize = 0
        psiegel-gravis:
                halfDuplexCapsLock = false
                halfDuplexNumLock = false
                halfDuplexScrollLock = false
                xtestIsXineramaUnaware = false
                preserveFocus = false
                switchCorners = none
                switchCornerSize = 0
end

section: aliases
end

section: links
        psiegel-desktop:
                right = psiegel-laptop
        psiegel-laptop:
                right = psiegel-gravis
                left = psiegel-desktop
        psiegel-gravis:
                left = psiegel-laptop
end

section: options
        relativeMouseMoves = true
        screenSaverSync = true
        win32KeepForeground = false
        clipboardSharing = true
        switchCorners = none
        switchCornerSize = 0
        keystroke(Alt+Shift+Left) = switchInDirection(left)
        keystroke(Alt+Shift+Right) = switchInDirection(right)
end
