unbind C-b
set -g prefix C-a
bind C-a send-prefix

################################
# terminal colors
################################
set -g default-terminal "tmux-256color"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

###############################
# behavior
###############################
set-option -g history-limit 5000

# set vim control
setw -g mode-keys vi
bind -n F2 copy-mode

#mouse control
set-option -g mouse on

# Setup yanking to clipboard
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @yank_selection_mouse 'clipboard' 

################################
# panes
################################
set -g display-panes-time 400

# moving over panes
bind-key -n C-Left select-pane -L #\;  display-pane
bind-key -n C-Right select-pane -R #\;  display-pane
bind-key -n C-Up select-pane -U #\;  display-pane
bind-key -n C-Down select-pane -D #\;  display-pane

bind-key -n C-l select-pane -L #\;  display-pane 
bind-key -n C-h select-pane -R #\;  display-pane
bind-key -n C-j select-pane -U #\;  display-pane
bind-key -n C-k select-pane -D #\;  display-pane

#key bindings for pane resizing
bind-key -n C-S-Left resize-pane -L
bind-key -n C-S-Right resize-pane -R
bind-key -n C-S-Up resize-pane -U
bind-key -n C-S-Down resize-pane -D

#kill pane
#bind-key -n C-w kill-pane

#bind split
unbind M-Right
unbind M-Down
bind -n M-Right split-window -h -c "#{pane_current_path}"
bind -n M-Down split-window -v -c "#{pane_current_path}"

############################
#color of panes
############################

# border colours
set -g pane-border-style fg=colour233
set -g pane-active-border-style "bg=default fg=colour27"

#status bar
set -g status-position bottom
set -g status-bg colour234
set -g status-fg colour15
set -g status-left "#[fg=colour15,bg=colour26] #S #[fg=colour103,bg=colour236,nobold,nounderscore,noitalics]"
set -g status-right "#[fg=colour239] #(echo )S #[fg=colour103,bg=colour236,nobold,nounderscore,noitalics]"

# Run the plugin manager
run -b '~/.tmux/plugins/tpm/tpm'
